### ISSUE TITLE
收缩后加载完成不恢复原状不可以？

### ISSUE THREAD

**Issue by AndSync** [FlodCoding/HardLoadingButton#1]

**Comment by FlodCoding** [comment]
> _No description provided._

可以呀，可以把代码放上来看看吗？

**Comment by FlodCoding** [comment]
> > _No description provided._
> 
> 可以呀，可以把代码放上来看看吗？

抱歉最近太忙了，没看到Issues

**Comment by FlodCoding** [comment]
> _No description provided._

默认是恢复原状的，你可以在onFailed() 或者onCompleted()  改变你想要的状态
