### ISSUE TITLE
背景selector异常

### ISSUE THREAD

**Issue by bailandi** [FlodCoding/HardLoadingButton#2]
```
  @SuppressLint("ClickableViewAccessibility")
    @Override
    public boolean onTouchEvent(MotionEvent event) {
        if (event.getAction() == MotionEvent.ACTION_UP) {
        //disable click
   if (disableClickOnLoading && curStatus != STATE.IDE) {
            return true;
        }
        }
        return super.onTouchEvent(event);
    }
```
建议修改为
```
    @Override
    public boolean dispatchTouchEvent(MotionEvent event) {
        if (disableClickOnLoading && curStatus != STATE.IDE) {
            return true;
        }
        return super.dispatchTouchEvent(event);
    }
```
否则会导致设置了不同状态的selector出现异常

**Comment by FlodCoding** [comment]
> ```
>   @SuppressLint("ClickableViewAccessibility")
>     @Override
>     public boolean onTouchEvent(MotionEvent event) {
>         if (event.getAction() == MotionEvent.ACTION_UP) {
>         //disable click
>    if (disableClickOnLoading && curStatus != STATE.IDE) {
>             return true;
>         }
>         }
>         return super.onTouchEvent(event);
>     }
> ```
> 
> 建议修改为
> 
> ```
>     @Override
>     public boolean dispatchTouchEvent(MotionEvent event) {
>         if (disableClickOnLoading && curStatus != STATE.IDE) {
>             return true;
>         }
>         return super.dispatchTouchEvent(event);
>     }
> ```
> 
> 否则会导致设置了不同状态的selector出现异常

感谢指出，已修改
