### ISSUE TITLE
问题

### ISSUE THREAD

**Issue by zhuoCreator** [FlodCoding/HardLoadingButton#3]
enableShrink=false   调用completed后loading不会消失，按钮也不能点：enable=false，应该是个bug

**Comment by zhuoCreator** [comment]
不对劲，调用cancel竟然可以 ，这逻辑不明白  成功后不也代表取消了吗

**Comment by FlodCoding** [comment]
> enableShrink=false 调用completed后loading不会消失，按钮也不能点：enable=false，应该是个bug

能否将代码贴出来看下

**Comment by zhuoCreator** [comment]
`<com.flod.loadingbutton.LoadingButton
        android:layout_width="230dp"
        android:layout_height="40dp"
        android:id="@+id/loadingButton"
        android:text="登录"
        app:enableShrink="false"
        android:textColor="#ffffff"
        android:gravity="center"
        android:drawablePadding="10dp"
        android:background="@drawable/gradient_btn_shape"
        />


public class MainActivity extends AppCompatActivity implements View.OnClickListener {

    private LoadingButton loadingButton;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        initView();
    }

    private void initView() {
        loadingButton = (LoadingButton) findViewById(R.id.loadingButton);
        loadingButton.setOnClickListener(this);
        loadingButton.setLoadingEndDrawableSize((int) (loadingButton.getTextSize() * 2));
    }

    @Override
    public void onClick(View v) {
        switch (v.getId()) {
            case R.id.loadingButton:
                loadingButton.start();
                loadingButton.setText("");
                new Handler().postDelayed(new Runnable() {
                    @Override
                    public void run() {
                        loadingButton.complete();
                    }
                }, 3000);
                Toast.makeText(this, "111111", Toast.LENGTH_SHORT).show();
                break;
        }
    }
}

`

**Comment by FlodCoding** [comment]
> > enableShrink=false 调用completed后loading不会消失，按钮也不能点：enable=false，应该是个bug
> 
> 能否将代码贴出来看下

感谢指出，问题已修复
[关联错误位置](https://github.com/FlodCoding/LoadingButton/commit/2110a75a629d4502b68db99ff4fb7bddc6452e93#diff-d1c8df0988fa220cf4033ee4380a58a1R419)

**Comment by zhuoCreator** [comment]
😜------------------ 原始邮件 ------------------
发件人: "FlodCoding"<notifications@github.com>
发送时间: 2019年11月5日(星期二) 晚上8:22
收件人: "FlodCoding/LoadingButton"<LoadingButton@noreply.github.com>;
抄送: "zhuoEr"<1027002821@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [FlodCoding/LoadingButton] 问题 (#3)


  
enableShrink=false 调用completed后loading不会消失，按钮也不能点：enable=false，应该是个bug
  
能否将代码贴出来看下
  
感谢指出，问题已修复
 关联错误位置
 
&mdash;
