### ISSUE TITLE
4.2模拟器上运行时loading显示不全

### ISSUE THREAD

**Issue by bailandi** [FlodCoding/HardLoadingButton#5]
![TIM图片20191106135935](https://user-images.githubusercontent.com/22045071/68272267-17a8e980-009e-11ea-9fb0-0b5054c017d0.png)
如图 在AVD创建的4.2版本（x86）模拟器上运行时，loading的圆圈显示异常（感觉就像中间有一小块截面覆盖在上面一样），尝试在初始化时关闭硬件加速无效

**Comment by FlodCoding** [comment]
> ![TIM图片20191106135935](https://user-images.githubusercontent.com/22045071/68272267-17a8e980-009e-11ea-9fb0-0b5054c017d0.png)
> 如图 在AVD创建的4.2版本（x86）模拟器上运行时，loading的圆圈显示异常（感觉就像中间有一小块截面覆盖在上面一样），尝试在初始化时关闭硬件加速无效

看样子可能是硬件加速产生的问题，晚上回去再看看吧

**Comment by FlodCoding** [comment]
> ![TIM图片20191106135935](https://user-images.githubusercontent.com/22045071/68272267-17a8e980-009e-11ea-9fb0-0b5054c017d0.png)
> 如图 在AVD创建的4.2版本（x86）模拟器上运行时，loading的圆圈显示异常（感觉就像中间有一小块截面覆盖在上面一样），尝试在初始化时关闭硬件加速无效

感谢指出，问题已修复
https://github.com/FlodCoding/LoadingButton/commit/615cc22a8738b0f06680af0b154b0f9f9ac524a0#diff-d1c8df0988fa220cf4033ee4380a58a1L733

查阅了下文档
`LAYER_TYPE_HARDWARE: The view is rendered in hardware into a hardware texture if the application is hardware accelerated. If the application is not hardware accelerated, this layer type behaves the same as LAYER_TYPE_SOFTWARE.
LAYER_TYPE_SOFTWARE: The view is rendered in software into a bitma`
[关联文档](https://developer.android.com/guide/topics/graphics/hardware-accel)

1、当关闭硬件加速后效果与LAYER_TYPE_SOFTWARE相同，但是使用LAYER_TYPE_SOFTWARE却正常显示
2、高于5.0的模拟器也显示正常

有可能是4.2以下的模拟器硬件加速有问题

**Comment by bailandi** [comment]
؏؏☝ᖗ乛◡乛ᖘ☝؏؏完美
